# Generated by Django 4.0.5 on 2022-06-28 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('quarter', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('group_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_name', models.CharField(blank=True, max_length=255)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifics_1', models.CharField(blank=True, max_length=255)),
                ('specifics_2', models.CharField(blank=True, max_length=255)),
                ('specifics_3', models.CharField(blank=True, max_length=255)),
                ('specifics_4', models.CharField(blank=True, max_length=255)),
                ('specifics_5', models.CharField(blank=True, max_length=255)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_status', models.CharField(blank=True, max_length=255)),
                ('received_quatation_status', models.CharField(blank=True, max_length=255)),
                ('award_winning_bidder_status', models.CharField(blank=True, max_length=255)),
                ('obligate_po_status', models.CharField(blank=True, max_length=255)),
                ('served_status', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('first_quantity', models.CharField(blank=True, max_length=255)),
                ('second_quantity', models.CharField(blank=True, max_length=255)),
                ('third_quantity', models.CharField(blank=True, max_length=255)),
                ('fourth_quantity', models.CharField(blank=True, max_length=255)),
                ('fifth_quantity', models.CharField(blank=True, max_length=255)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.app')),
                ('item_desc_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.itemdescription')),
            ],
        ),
        migrations.CreateModel(
            name='PpmpTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('cc_name', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceOfFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_details', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('order_details_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.orderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Ppmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('cc_num_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.costcenter')),
                ('sof_num_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.sourceoffund')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='ppmp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.ppmp'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='price_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.prices'),
        ),
        migrations.CreateModel(
            name='CostCenterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.costcenter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenterBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_budget', models.CharField(blank=True, max_length=255)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.category')),
                ('cc_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.costcenter')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='item_desc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.itemdescription'),
        ),
        migrations.AddField(
            model_name='app',
            name='source_of_fund_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.sourceoffund'),
        ),
    ]
