# Generated by Django 4.0.5 on 2022-06-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='item_desc_id',
            new_name='item_desc',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='source_of_fund_id',
            new_name='source_of_fund',
        ),
        migrations.RenameField(
            model_name='costcenterbudget',
            old_name='cat_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='costcenterbudget',
            old_name='cc_id',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='costcenteruser',
            old_name='cc_id',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='costcenteruser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='cat_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='itemdescription',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='item_desc_id',
            new_name='item_desc',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='ppmp_id',
            new_name='ppmp',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='price_id',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='ppmp',
            old_name='cc_num_id',
            new_name='cc_num',
        ),
        migrations.RenameField(
            model_name='ppmp',
            old_name='sof_num_id',
            new_name='sof_num',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='order_details_id',
            new_name='order_details',
        ),
    ]
