# Generated by Django 4.0.5 on 2022-06-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0002_rename_item_desc_id_app_item_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdescription',
            old_name='specifics_1',
            new_name='specifics',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='first_quantity',
            new_name='fq_quantity',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='fourth_quantity',
            new_name='sq_quantity',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='second_quantity',
            new_name='tq_quantity',
        ),
        migrations.RemoveField(
            model_name='itemdescription',
            name='specifics_2',
        ),
        migrations.RemoveField(
            model_name='itemdescription',
            name='specifics_3',
        ),
        migrations.RemoveField(
            model_name='itemdescription',
            name='specifics_4',
        ),
        migrations.RemoveField(
            model_name='itemdescription',
            name='specifics_5',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='third_quantity',
        ),
        migrations.AlterField(
            model_name='prices',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.itemdescription'),
        ),
    ]
