# Generated by Django 4.0.5 on 2022-06-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0003_rename_specifics_1_itemdescription_specifics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='fq_quantity',
            new_name='first_quart_quant',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='sq_quantity',
            new_name='fourth_quart_quant',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='tq_quantity',
            new_name='second_quart_quant',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='third_quart_quant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
