# Generated by Django 4.0.5 on 2022-07-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0004_rename_fq_quantity_orderdetails_first_quart_quant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdescription',
            old_name='specifics',
            new_name='spec_1',
        ),
        migrations.AddField(
            model_name='itemdescription',
            name='spec_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itemdescription',
            name='spec_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itemdescription',
            name='spec_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='itemdescription',
            name='spec_5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
