# Generated by Django 4.0.5 on 2022-07-22 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0005_rename_specifics_itemdescription_spec_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppmp',
            old_name='cc_num',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='ppmp',
            old_name='sof_num',
            new_name='sof',
        ),
    ]
