# Generated by Django 4.0.5 on 2022-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0006_rename_cc_num_ppmp_cc_rename_sof_num_ppmp_sof'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenterbudget',
            name='curr_budget',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
