# Generated by Django 4.0.5 on 2022-07-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0008_costcenterbudget_date_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
