# Generated by Django 4.0.5 on 2022-07-23 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0009_alter_app_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='fifth_quantity',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.app'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='app_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='award_winning_bidder_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='first_quart_quant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='fourth_quart_quant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='obligate_po_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='ppmp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.ppmp'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.prices'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='received_quatation_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='second_quart_quant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='served_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='third_quart_quant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
