# Generated by Django 4.0.5 on 2022-07-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0010_remove_orderdetails_fifth_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
