# Generated by Django 4.0.5 on 2022-07-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0011_orderdetails_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='received_quatation_status',
            new_name='received_quotation_status',
        ),
    ]
