# Generated by Django 4.0.5 on 2022-07-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0012_rename_received_quatation_status_orderdetails_received_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
