# Generated by Django 4.0.5 on 2022-07-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0013_alter_orderdetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmptrack',
            name='orderdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.orderdetails'),
        ),
    ]
