# Generated by Django 4.0.5 on 2022-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0014_ppmptrack_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppmptrack',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ppmptrack',
            name='cc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ppmptrack',
            name='datetime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
