# Generated by Django 4.0.5 on 2022-09-23 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0015_alter_ppmptrack_barcode_alter_ppmptrack_cc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmp',
            name='is_lock',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='category', to='ppmp.category'),
        ),
        migrations.AlterField(
            model_name='itemdescription',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item', to='ppmp.item'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='app', to='ppmp.app'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='item_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_desc', to='ppmp.itemdescription'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='ppmp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ppmp', to='ppmp.ppmp'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='ppmp.prices'),
        ),
    ]
