# Generated by Django 4.0.5 on 2022-09-23 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppmp', '0016_ppmp_is_lock_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmp',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='ppmp_key_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('is_lock', models.BooleanField(blank=True, default=False)),
                ('ppmp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ppmp.ppmp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
