# Generated by Django 4.0.5 on 2022-10-21 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppmp', '0017_ppmp_is_deleted_ppmp_key_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppmp',
            name='is_lock',
        ),
        migrations.AddField(
            model_name='ppmp_key_log',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.category'),
        ),
        migrations.AddField(
            model_name='ppmp_key_log',
            name='cc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.costcenter'),
        ),
        migrations.AddField(
            model_name='ppmp_key_log',
            name='sof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.sourceoffund'),
        ),
        migrations.AlterField(
            model_name='ppmp_key_log',
            name='ppmp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.ppmp'),
        ),
        migrations.AlterField(
            model_name='ppmp_key_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
