# Generated by Django 4.0.5 on 2022-10-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0018_remove_ppmp_is_lock_ppmp_key_log_cat_ppmp_key_log_cc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_code', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ppmp_key_log',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='ppmp_key_log',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='ppmp_key_log',
            name='ppmp',
        ),
        migrations.RemoveField(
            model_name='ppmp_key_log',
            name='sof',
        ),
        migrations.RemoveField(
            model_name='ppmp_key_log',
            name='user',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='source_of_fund',
            new_name='sof',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='general_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='date',
            new_name='cat_code',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='first_quart_quant',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='fourth_quart_quant',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='qr_code',
            new_name='first_quant',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='second_quart_quant',
            new_name='fourth_quant',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='third_quart_quant',
            new_name='second_quant',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='app',
            name='item_desc',
        ),
        migrations.RemoveField(
            model_name='costcenterbudget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='app',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='item_desc',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ppmp',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='unit',
        ),
        migrations.AddField(
            model_name='costcenterbudget',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item', to='ppmp.item'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='third_quant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='costcenterbudget',
            name='cc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.costcenter'),
        ),
        migrations.AlterField(
            model_name='ppmp',
            name='cc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.costcenter'),
        ),
        migrations.AlterField(
            model_name='ppmp',
            name='sof',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.sourceoffund'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.item'),
        ),
        migrations.DeleteModel(
            name='ItemDescription',
        ),
        migrations.DeleteModel(
            name='ppmp_key_log',
        ),
        migrations.AddField(
            model_name='procurementmode',
            name='app',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='APP', to='ppmp.app'),
        ),
        migrations.AddField(
            model_name='procurementmode',
            name='orderdetail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='OrderItem', to='ppmp.orderdetails'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ppmp.item'),
        ),
    ]
