# Generated by Django 4.0.5 on 2022-10-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0021_alter_orderdetails_item_alter_orderdetails_ppmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
