# Generated by Django 4.0.5 on 2022-10-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0022_alter_prices_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppmp',
            name='cc',
        ),
        migrations.AddField(
            model_name='ppmp',
            name='cc_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
