# Generated by Django 4.0.5 on 2022-11-26 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0023_remove_ppmp_cc_ppmp_cc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementmode',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='APP', to='ppmp.app'),
        ),
        migrations.AlterField(
            model_name='procurementmode',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
