# Generated by Django 4.0.5 on 2022-12-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppmp', '0025_requestitem_requestitemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='unit_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='specification_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
